---
- name:
  hosts: webservers
  vars: 
    http_port: 80
    max_clients: 200
    remote_user: root 
  tasks:
  - name: first task 
    yum: 
      name: httpd
      state: latest

  - name: second task
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: third task
    service: 
      name: httpd 
      state: started
      enabled: yes
